# Generated by Django 4.2 on 2025-01-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlanMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.paymentplan')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlanFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.paymentplanmilestone')),
            ],
        ),
    ]
