# Generated by Django 4.2 on 2025-01-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplanmilestone',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentplanmilestone',
            name='recurring_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymentplanmilestone',
            name='remarks',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentplanmilestone',
            name='total_percent',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
    ]
